name: NoDevFee XMRIG Windows
on:
  # Manueel starte
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build_win:
    name: Build Windows artifacts
    runs-on: windows-latest
    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@v4
      - name: msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc make zip
      - uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
      - name: Checkout deps
        shell: powershell
        run: |
            git clone https://github.com/xmrig/xmrig-deps.git
      - name: Build project on Windows
        shell: msys2 {0}
        run: |
            "c:\Program Files\CMake\bin\cmake.exe" . -G "Unix Makefiles" -DXMRIG_DEPS=D:/a/xmrig/xmrig/xmrig-deps/gcc/x64
            make -j$(nproc)
            cp src\config.json .
            zip -r windows_build.zip xmrig.exe config.json WinRing0x64.sys
      - name: Upload Windows build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows_build
          path: windows_build.zip
