name: NoDevFee XMRIG Windows
on:
  # Manueel starte
  workflow_dispatch:

jobs:
  build_win:
    name: Build Windows artifacts
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: mingw-w64-x86_64-gcc git make cmake
      - name: Checkout deps
        run:  git clone https://github.com/xmrig/xmrig-deps.git
      - name: Build project on Windows
        run: |
          cmake . -G "Unix Makefiles" -DXMRIG_DEPS=xmrig-deps\gcc\x64
          make
          copy src\config.json .
          copy bin\WinRing0\WinRing0x64.sys .
          7z a -tzip -mx windows_build.zip xmrig.exe config.json WinRing0x64.sys
      - name: Upload Windows build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows_build
          path: windows_build.zip
