name: NoDevFee XMRIG Windows
on:
  # Manueel starte
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build_win:
    name: Build Windows artifacts
    runs-on: windows-latest
    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@v4
      - name: msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-gcc git make wget
      - name: install cmake
        shell: powershell
        run: |
            Invoke-WebRequest -Uri https://github.com/Kitware/CMake/releases/download/v4.0.2/cmake-4.0.2-windows-x86_64.msi -OutFile cmake.msi
            .\cmake.msi /quiet
      - name: Checkout deps
        shell: powershell
        run: |
            git clone https://github.com/xmrig/xmrig-deps.git
      - name: Build project on Windows
        shell: msys2 {0}
        run: |
            "c:\Program Files\CMake\bin\cmake.exe" . -G "Unix Makefiles" -DXMRIG_DEPS=D:/a/xmrig/xmrig/xmrig-deps/gcc/x64 
            make -j$(nproc)
            copy src\config.json .
            copy bin\WinRing0\WinRing0x64.sys .
            7z a -tzip -mx windows_build.zip xmrig.exe config.json WinRing0x64.sys
      - name: Upload Windows build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows_build
          path: windows_build.zip
